/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoyageCharterEstimationRouteImport } from './routes/voyage-charter-estimation'
import { Route as TimeCharterOutFixtureRouteImport } from './routes/time-charter-out-fixture'
import { Route as TimeCharterOutRouteImport } from './routes/time-charter-out'
import { Route as PortActivitiesRouteImport } from './routes/port-activities'
import { Route as IndexRouteImport } from './routes/index'

const VoyageCharterEstimationRoute = VoyageCharterEstimationRouteImport.update({
  id: '/voyage-charter-estimation',
  path: '/voyage-charter-estimation',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeCharterOutFixtureRoute = TimeCharterOutFixtureRouteImport.update({
  id: '/time-charter-out-fixture',
  path: '/time-charter-out-fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeCharterOutRoute = TimeCharterOutRouteImport.update({
  id: '/time-charter-out',
  path: '/time-charter-out',
  getParentRoute: () => rootRouteImport,
} as any)
const PortActivitiesRoute = PortActivitiesRouteImport.update({
  id: '/port-activities',
  path: '/port-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/port-activities': typeof PortActivitiesRoute
  '/time-charter-out': typeof TimeCharterOutRoute
  '/time-charter-out-fixture': typeof TimeCharterOutFixtureRoute
  '/voyage-charter-estimation': typeof VoyageCharterEstimationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/port-activities': typeof PortActivitiesRoute
  '/time-charter-out': typeof TimeCharterOutRoute
  '/time-charter-out-fixture': typeof TimeCharterOutFixtureRoute
  '/voyage-charter-estimation': typeof VoyageCharterEstimationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/port-activities': typeof PortActivitiesRoute
  '/time-charter-out': typeof TimeCharterOutRoute
  '/time-charter-out-fixture': typeof TimeCharterOutFixtureRoute
  '/voyage-charter-estimation': typeof VoyageCharterEstimationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/port-activities'
    | '/time-charter-out'
    | '/time-charter-out-fixture'
    | '/voyage-charter-estimation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/port-activities'
    | '/time-charter-out'
    | '/time-charter-out-fixture'
    | '/voyage-charter-estimation'
  id:
    | '__root__'
    | '/'
    | '/port-activities'
    | '/time-charter-out'
    | '/time-charter-out-fixture'
    | '/voyage-charter-estimation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortActivitiesRoute: typeof PortActivitiesRoute
  TimeCharterOutRoute: typeof TimeCharterOutRoute
  TimeCharterOutFixtureRoute: typeof TimeCharterOutFixtureRoute
  VoyageCharterEstimationRoute: typeof VoyageCharterEstimationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voyage-charter-estimation': {
      id: '/voyage-charter-estimation'
      path: '/voyage-charter-estimation'
      fullPath: '/voyage-charter-estimation'
      preLoaderRoute: typeof VoyageCharterEstimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-charter-out-fixture': {
      id: '/time-charter-out-fixture'
      path: '/time-charter-out-fixture'
      fullPath: '/time-charter-out-fixture'
      preLoaderRoute: typeof TimeCharterOutFixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-charter-out': {
      id: '/time-charter-out'
      path: '/time-charter-out'
      fullPath: '/time-charter-out'
      preLoaderRoute: typeof TimeCharterOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-activities': {
      id: '/port-activities'
      path: '/port-activities'
      fullPath: '/port-activities'
      preLoaderRoute: typeof PortActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortActivitiesRoute: PortActivitiesRoute,
  TimeCharterOutRoute: TimeCharterOutRoute,
  TimeCharterOutFixtureRoute: TimeCharterOutFixtureRoute,
  VoyageCharterEstimationRoute: VoyageCharterEstimationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
